#========================================================================
# Copyright Universidade Federal do Espirito Santo (Ufes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: '3.8'

services:

    # web app
    boca-web:
        image: ghcr.io/joaofazolo/boca-docker/boca-web
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1024M
                reservations:
                    cpus: '0.25'
                    memory: 512M
            restart_policy:
                condition: any
        depends_on:
            - boca-postgres
        environment:
            # Database configuration
            - DB_HOST=boca-postgres
            - DB_PORT=5432
            - DB_NAME=bocadb
            # unprivileged boca user
            - DB_USER=bocauser
            - DB_PASSWORD=dAm0HAiC
            # privileged boca user
            - DB_SUPER_USER=bocauser
            - DB_SUPER_PASSWORD=dAm0HAiC
            # initial password that is used by the admin user (web app)
            # If not set, the default value is 'boca'
            - BOCA_PASSWORD=boca
            # secret key to be used in HTTP headers
            # MUST set it with any random large enough sequence
            - BOCA_KEY=GG56KFJtNDBGjJprR6ex
        ports: 
            - 8000:80
        networks:
            - frontend
            - backend

    # online judge
    boca-jail:
        image: ghcr.io/joaofazolo/boca-docker/boca-jail
        deploy:
            mode: replicated
            replicas: 1
            placement:
                max_replicas_per_node: 8
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1024M
                reservations:
                    cpus: '0.25'
                    memory: 512M
            restart_policy:
                condition: any
        depends_on:
            - boca-postgres
        environment:
            # Database configuration
            - DB_HOST=boca-postgres
            - DB_PORT=5432
            - DB_NAME=bocadb
            # unprivileged boca user
            - DB_USER=bocauser
            - DB_PASSWORD=dAm0HAiC
            - PASSWD=dAm0HAiC
        networks:
            - backend

    # database
    boca-postgres:
        image: postgres
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    cpus: '0.50'
                    memory: 2048M
                reservations:
                    cpus: '0.25'
                    memory: 1024M
            restart_policy:
                condition: any
        environment:
            # Database configuration
            # privileged boca user
            POSTGRES_USER: bocauser
            POSTGRES_PASSWORD: dAm0HAiC
        networks:
            - backend

networks:
    frontend: # visible to proxy
    backend: # hidden from the outside world
        internal: true
