version: '3'

services:
    boca:
        volumes:
            - ./src:/var/www/boca/src

    boca-postgres:
        ports: 
            - 5432:5432
        volumes: 
            - db-data:/var/lib/postgresql/data

    boca-adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db-data: