version: '2'

services:
    boca:
        privileged: true
        depends_on:
            - boca-postgres
        build: 
            context: .
            dockerfile: docker/dev/web/Dockerfile
        environment: 
            - DB_HOST=boca-postgres
            - DB_PORT=5432
            - DB_NAME=bocadb
            - DB_USER=bocauser
            - DB_PASSWORD=dAm0HAiC
        ports: 
            - 8000:80
        # volumes:
        #     - ./src:/var/www/boca/src

    boca-jail:
        privileged: true
        depends_on:
            - boca-postgres
        build: 
            context: .
            dockerfile: docker/dev/jail/Dockerfile
        environment: 
            - DB_HOST=boca-postgres
            - DB_PORT=5432
            - DB_NAME=bocadb
            - DB_USER=bocauser
            - DB_PASSWORD=dAm0HAiC
            - PASSWD=dAm0HAiC

    boca-postgres:
        image: postgres
        container_name: boca-postgres
        environment:
            POSTGRES_USER: bocauser
            POSTGRES_PASSWORD: dAm0HAiC
        ports: 
            - 5432:5432
        # volumes: 
        #     - db-data:/var/lib/postgresql/data

volumes:
    db-data: