name: Build and publish Docker image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub Actions Documentation
# https://docs.github.com/en/github-ae@latest/actions

# Reusing workflows
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      image:
        description: "Image to build (i.e., boca-base, boca-web and boca-jail)"
        required: true
        type: string
      parent:
        description: 'Parent/base image used to build'
        required: true
        type: string
      is_default_parent:
        description: 'Default parent/base image'
        required: true
        type: boolean
      platform:
        description: "OS/platform-specific target build"
        required: true
        type: string
      tag:
        description: "Image tags (whitespace-separated)"
        required: true
        type: string

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_HOST: ghcr.io
  # Use github.repository (<account>/<repo>)
  REPOSITORY_NAME: ${{ github.repository }}
  # Use github.repository_owner (<account>)
  OWNER_NAME: ${{ github.repository_owner }}
  # Use GitHub local cache exporter
  REGISTRY_PATH: ${{ github.workspace }}/registry
  CACHE_PATH: /tmp/.buildx-cache

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # for actions/checkout to fetch code
      contents: read
      # can upload and download package, as well as read/write package metadata
      packages: write
    name: build (${{ inputs.image }}, ${{ inputs.parent }})

    steps:
      # Checkout a repository, so the workflow can access it
      # https://github.com/marketplace/actions/checkout
      - 
        name: Checkout repository
        uses: actions/checkout@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Create and boot a builder that can be used in the following steps of
      # the workflow
      # https://github.com/docker/setup-buildx-action
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      # Set environment variables (NOTE: alternatively could have used an
      # output parameter between steps, see above)
      # https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - 
        name: Write variables to GITHUB_ENV
        run: |

          PARENT='${{ inputs.parent }}'
          # Replace 'ubuntu:' with ''
          FLAVOR=${PARENT//ubuntu:/}
          echo $FLAVOR
          echo "flavor_name=$FLAVOR" >> $GITHUB_ENV

          DIR='${{ inputs.image }}'
          # Remove 'boca-' from image name
          DIR=${DIR//boca-/}
          echo $DIR
          echo "folder_name=$DIR" >> $GITHUB_ENV

      # Download artifacts that have been uploaded from previous jobs
      # https://github.com/actions/download-artifact
      -
        name: Download Docker registry data from boca-base image
        if: inputs.image != 'boca-base'
        uses: actions/download-artifact@v3
        with:
          name: docker-registry-data
          path: ${{ env.REGISTRY_PATH }}/boca-base-${{ env.flavor_name }}/

      - 
        name: Start local Docker registry (boca-base)
        run: |

          docker run --rm --detach --publish 5000:5000 \
            --volume ${REGISTRY_PATH}/boca-base-${flavor_name}:/var/lib/registry \
            --name registry registry:2

      # Cache storage backends with GitHub Actions
      # https://github.com/actions/cache
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATH }}/${{ inputs.image }}-${{ env.flavor_name }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Login to a Docker registry (push remotely)
      # https://github.com/docker/login-action
      - 
        name: Login to GitHub Container Registry (push remotely)
        if: inputs.image != 'boca-base'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - 
        name: Extract Docker metadata (boca-base)
        id: meta_base
        uses: docker/metadata-action@v4
        with:
          images: localhost:5000/${{ env.REPOSITORY_NAME }}/boca-base

      - 
        name: Extract Docker metadata (${{ inputs.image }})
        if: inputs.image != 'boca-base'
        id: meta_image
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ env.REPOSITORY_NAME }}/${{ inputs.image }}
          tags: |
            # nightly build
            type=schedule,pattern=nightly,suffix=-${{ env.flavor_name }}
            type=schedule,pattern=nightly,enable=${{ inputs.is_default_parent }}
            # new release
            type=semver,pattern={{raw}},priority=900,suffix=-${{ env.flavor_name }}
            type=semver,pattern={{raw}},priority=1000,enable=${{ inputs.is_default_parent }}
            type=semver,pattern={{major}}.{{minor}},priority=900,suffix=-${{ env.flavor_name }}
            type=semver,pattern={{major}}.{{minor}},priority=1000,enable=${{ inputs.is_default_parent }}
            # tag event (same as new release)
            type=ref,event=tag,priority=900,suffix=-${{ env.flavor_name }}
            type=ref,event=tag,priority=1000,enable=${{ inputs.is_default_parent }}
            # workflow_dispatch (debug)
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.is_default_parent && github.event_name == 'workflow_dispatch' }}
            type=raw,value=${{ inputs.tag }},suffix=-${{ env.flavor_name }},enable=${{ github.event_name == 'workflow_dispatch' }}
            # branch event
            type=ref,event=branch,priority=900,suffix=-${{ env.flavor_name }}
            type=ref,event=branch,priority=1000,enable=${{ inputs.is_default_parent }}
          # This identifies which variant will be published as "latest", which
          # isn't necessarily the newest version of the source code
          flavor: |
            latest=${{ inputs.is_default_parent && github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - 
        name: Build and push image locally (boca-base)
        id: build
        if: inputs.image == 'boca-base'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dev/${{ env.folder_name }}/Dockerfile
          platforms: ${{ inputs.platform }}
          # tags: ${{ steps.meta_base.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ inputs.parent }}
          outputs: type=image,name=localhost:5000/${{ env.REPOSITORY_NAME }}/boca-base,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=local,src=${{ env.CACHE_PATH }}/boca-base-${{ env.flavor_name }}
          cache-to: type=local,dest=${{ env.CACHE_PATH }}/boca-base-${{ env.flavor_name }}-new,mode=max

      - 
        name: Build and push image remotely (${{ inputs.image }})
        if: inputs.image != 'boca-base'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dev/${{ env.folder_name }}/Dockerfile
          platforms: ${{ inputs.platform }}
          push: true
          tags: |
            ${{ steps.meta_image.outputs.tags }}
          labels: ${{ steps.meta_image.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ steps.meta_base.outputs.tags }}
          provenance: false
          cache-from: type=local,src=${{ env.CACHE_PATH }}/${{ inputs.image }}-${{ env.flavor_name }}
          cache-to: type=local,dest=${{ env.CACHE_PATH }}/${{ inputs.image }}-${{ env.flavor_name }}-new,mode=max

      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests/${{ inputs.image }}
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${{ inputs.image }}/${digest#sha256:}"

      -
        name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/${{ inputs.image }}/*
          if-no-files-found: error
          retention-days: 1

      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |

          rm -rf ${{ env.CACHE_PATH }}/${{ inputs.image }}-${{ env.flavor_name }}
          mv ${{ env.CACHE_PATH }}/${{ inputs.image }}-${{ env.flavor_name }}-new ${{ env.CACHE_PATH }}/${{ inputs.image }}-${{ env.flavor_name }}

      - name: Stop local Docker registry
        run: |

          docker stop registry

      # # Upload artifacts from workflow allowing to share data between jobs
      # # https://github.com/actions/upload-artifact
      # - 
      #   name: Upload Docker registry data for boca-web and boca-jail images
      #   if: inputs.image == 'boca-base'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: docker-registry-data
      #     path: ${{ env.REGISTRY_PATH }}/boca-base-${{ env.flavor_name }}/
