name: Call a reusable workflow and use its outputs

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub Actions Documentation
# https://docs.github.com/en/github-ae@latest/actions

on:
  # Run daily at 9:15 AM UTC (nightly builds)
  schedule:
    # Publish "nightly" build as release
    - cron: '15 9 * * *'
  push:
    # Publish semver tags as releases (e.g., 1.0.0)
    tags: [ '*.*.*' ]
  # or on button click
  # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (only one)"
        required: true
        type: string

# Save computation power by stopping obsolete jobs for the current workflow
# https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Calling a reusable workflow
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  setup:
    uses: ./.github/workflows/read-build-matrix-from-file.yml
    with:
      matrix-path: docker/build/matrix.json

  build-base:
    uses: ./.github/workflows/ghcr-image-build-push.yml
    with:
      images: '[ "boca-base" ]'
      parents: ${{ needs.setup.outputs.parent }}
      default_parent: ${{ needs.setup.outputs.default_parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: ${{ inputs.tag }}
    needs:
      - setup

  build-web:
    uses: ./.github/workflows/ghcr-image-build-push.yml
    with:
      images: '[ "boca-web" ]'
      parents: ${{ needs.setup.outputs.parent }}
      default_parent: ${{ needs.setup.outputs.default_parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: ${{ inputs.tag }}
    needs:
      - setup
      - build-base

  build-jail:
    uses: ./.github/workflows/ghcr-image-build-push.yml
    with:
      images: '[ "boca-jail" ]'
      parents: ${{ needs.setup.outputs.parent }}
      default_parent: ${{ needs.setup.outputs.default_parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: ${{ inputs.tag }}
    needs:
      - setup
      - build-base

  scan-base:
    uses: ./.github/workflows/image-scanning.yml
    with:
      images: '[ "boca-base" ]'
      parents: ${{ needs.setup.outputs.parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: ${{ inputs.tag }}
    needs:
      - setup
      - build-base
