name: CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub Actions Documentation
# https://docs.github.com/en/github-ae@latest/actions

on:
  # Run daily at 9:15 AM UTC (nightly builds)
  schedule:
    # Publish "nightly" build as release
    - cron: '15 9 * * *'
  push:
    # Publish semver tags as releases (e.g., 1.0.0)
    tags: [ '*.*.*' ]
  # or on button click
  # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch
  workflow_dispatch:
    inputs:
      tags:
        description: "Image tags (whitespace-separated)"
        required: true
        type: string
      latest:
        # The latest tag is automatically handled through the new tag/release
        # event. Set for conditionally tagging with the latest tag.
        description: "For conditionally tagging with the latest tag"
        required: false
        type: boolean

# Save computation power by stopping obsolete jobs for the current workflow
# https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup-tags:
    runs-on: ubuntu-latest
    # Map the workflow outputs to job outputs
    outputs:
      tags: ${{ steps.set-tags.outputs.tags }}

    steps:
      # Setting output parameters between steps, jobs and/or workflows
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      - 
        name: Set tags
        id: set-tags
        run: |

          TAGS="${{ inputs.tags }}"
          if [[ -z "${TAGS}" ]];
          then
            TAGS="${GITHUB_REF#refs/*/}"
          fi
          echo $TAGS
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

  # Calling a reusable workflow
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  setup-matrix:
    uses: ./.github/workflows/read-matrix.yml
    with:
      matrix-path: docker/build/matrix.json

  build-base:
    uses: ./.github/workflows/build-images.yml
    with:
      images: '[ "boca-base" ]'
      parents: ${{ needs.setup-matrix.outputs.parent }}
      default_parent: ${{ needs.setup-matrix.outputs.default_parent }}
      platforms: ${{ needs.setup-matrix.outputs.platform }}
      tags: ${{ needs.setup-tags.outputs.tags }}
    needs:
      - setup-tags
      - setup-matrix

  build-web:
    uses: ./.github/workflows/build-images.yml
    with:
      images: '[ "boca-web" ]'
      parents: ${{ needs.setup-matrix.outputs.parent }}
      default_parent: ${{ needs.setup-matrix.outputs.default_parent }}
      platforms: ${{ needs.setup-matrix.outputs.platform }}
      tags: ${{ needs.setup-tags.outputs.tags }}
    needs:
      - setup-tags
      - setup-matrix
      - build-base

  build-jail:
    uses: ./.github/workflows/build-images.yml
    with:
      images: '[ "boca-jail" ]'
      parents: ${{ needs.setup-matrix.outputs.parent }}
      default_parent: ${{ needs.setup-matrix.outputs.default_parent }}
      platforms: ${{ needs.setup-matrix.outputs.platform }}
      tags: ${{ needs.setup-tags.outputs.tags }}
    needs:
      - setup-tags
      - setup-matrix
      - build-base

  scan-base:
    uses: ./.github/workflows/scan-images.yml
    with:
      images: '[ "boca-base" ]'
      parents: ${{ needs.setup-matrix.outputs.parent }}
      platforms: ${{ needs.setup-matrix.outputs.platform }}
      tag: ${{ needs.setup-tags.outputs.tags }}
    needs:
      - setup-tags
      - setup-matrix
      - build-base

  scan-web:
    uses: ./.github/workflows/scan-images.yml
    with:
      images: '[ "boca-web" ]'
      parents: ${{ needs.setup-matrix.outputs.parent }}
      platforms: ${{ needs.setup-matrix.outputs.platform }}
      tag: ${{ needs.setup-tags.outputs.tags }}
    needs:
      - setup-tags
      - setup-matrix
      - build-web

  scan-jail:
    uses: ./.github/workflows/scan-images.yml
    with:
      images: '[ "boca-jail" ]'
      parents: ${{ needs.setup-matrix.outputs.parent }}
      platforms: ${{ needs.setup-matrix.outputs.platform }}
      tag: ${{ needs.setup-tags.outputs.tags }}
    needs:
      - setup-tags
      - setup-matrix
      - build-jail
