name: Delete Docker images on ghcr.io
on:
  # Run on button click
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_HOST: ghcr.io
  # Use github.repository (<account>/<repo>)
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # Delete versions of a package from GitHub Packages
      # https://github.com/marketplace/actions/delete-package-versions
      - 
        uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ env.REGISTRY_HOST }}/${{ env.REPOSITORY_NAME }}/boca-base
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
