# Ensure that the repository is given Admin access by going on
# Package settings -> Manage Actions access
# https://github.com/actions/delete-package-versions/issues/74
name: Delete untagged Docker images on ghcr.io

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # Run on button click
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_HOST: ghcr.io
  # Use github.repository (<account>/<repo>)
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  cleanup:
    permissions:
      packages: write
    strategy:
      matrix:
        image: [boca-base, boca-web, boca-jail]
    runs-on: ubuntu-latest

    steps:
      - 
        name: Get project name
        run: |
          PROJECT_NAME=${${{ github.repository }}\///${{ github.repository_owner }}/}
          echo ${PROJECT_NAME}

      # Delete versions of a package from GitHub Packages
      # https://github.com/marketplace/actions/delete-package-versions
      - 
        uses: actions/delete-package-versions@v4
        with: 
          package-name: '$PROJECT_NAME/${{ matrix.image }}'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
