name: Delete GitHub Actions caches for repository

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # Run on Sundays at 10:15 AM UTC
  schedule:
    - cron: '15 10 * * 0'
  # or on button click
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_HOST: ghcr.io
  # Use github.repository (<account>/<repo>)
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  cleanup:
    permissions:
      # `actions:write` permission is required to delete caches
      # See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      # Checkout a repository, so the workflow can access it
      # https://github.com/marketplace/actions/checkout
      - 
        name: Checkout repository
        uses: actions/checkout@v3

      # Force deletion of caches overriding default cache eviction policy
      # https://github.com/marketplace/actions/cache
      - 
        name: Delete all cache entries
        run: |
          gh extension install actions/gh-actions-cache

          while true
          do
            echo "Fetching list of cache keys"
            CACHEKEYS=$(gh actions-cache list --limit 100 \
                                              --sort size \
                                              --order desc \
                                              -R ${{ env.REPOSITORY_NAME }} \
                                              | cut -f 1)

            # Setting this to not fail the workflow while deleting cache keys. 
            set +e
            echo "Deleting caches..."
            for cachekey in $CACHEKEYS
            do
              gh actions-cache delete ${cachekey} --confirm
            done

            # Get length of $CACHEKEYS array
            len=${#CACHEKEYS[@]}
            if [[ $len -eq 1 ]];
            then
              echo "Done"
              break
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
