name: Cleanup workflow cache entries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # Run on button click
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_HOST: ghcr.io
  # Use github.repository (<account>/<repo>)
  REPOSITORY_NAME: ${{ github.repository }}
  # Use github.repository_owner (<account>)
  OWNER_NAME: ${{ github.repository_owner }}

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # Checkout a repository, so the workflow can access it
      # https://github.com/marketplace/actions/checkout
      - 
        name: Checkout repository
        uses: actions/checkout@v3
        
      - 
        name: Cleanup cache entries
        run: |
          gh extension install actions/gh-actions-cache

          #BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          #echo $BRANCH_NAME
          
          #echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R ${{ env.REPOSITORY_NAME }})

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
          #    gh actions-cache delete $cacheKey -R ${{ env.REPOSITORY_NAME }} --confirm
              echo $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
