---
name: Lint code base

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub Actions Documentation
# https://docs.github.com/en/github-ae@latest/actions

on:
  # Run on all pushes (except on master/main branch)
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  # PRs on master/main branch
  pull_request:
    branches: [master, main]
  # on button click
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      ref:
        # The branch, tag or SHA to checkout for linting. If empty, check out
        # the repository that triggered the workflow.
        description: |
          The branch, tag or SHA to checkout (empty for current branch)
        required: false
        type: string
  # or on calling as reusable workflow
  workflow_call:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
    inputs:
      ref:
        # The branch, tag or SHA to checkout for linting. If empty, check out
        # the repository that triggered the workflow.
        description: |
          The branch, tag or SHA to checkout (empty for current branch)
        required: false
        type: string
        
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    # Grant status permission for MULTI_STATUS
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      # Checkout a repository, so the workflow can access it
      # https://github.com/actions/checkout
      - 
        name: Checkout repository (no ref input)
        uses: actions/checkout@v3
        if: ${{ inputs.ref == '' }}
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - 
        name: Checkout repository (with ref input)
        uses: actions/checkout@v3
        if: ${{ inputs.ref != '' }}
        with:
          ref: '${{ inputs.ref }}'
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      # https://github.com/super-linter/super-linter
      - 
        name: Run Super-Linter on code base
        #uses: github/super-linter@v5
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_PHP_BUILTIN: true
          VALIDATE_BASH: true
          BASH_SEVERITY: error
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
