name: Check docker image

on:
  workflow_dispatch:

jobs:
  dockle:
    name: Dockle Container Analysis
    runs-on: ubuntu-latest
    steps:
      # Makes sure your .dockleignore file is available to the next step
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Dockle
        uses: erzz/dockle-action@v1
        with:
          image: ghcr.io/rlaiola/boca-docker/boca-jail:nightly
          #image: ubuntu:jammy
          failure-threshold: fatal
          # Change to 1 in order to stop the pipeline on failure
          # exit-code: 1
          timeout: 10m
