name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

# Save computation power by stopping obsolete jobs for the current workflow
# https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Calling a reusable workflow
  setup:
    uses: ./.github/workflows/read-build-matrix-from-file.yml
    with:
      matrix-path: docker/build/matrix.json

  build-base:
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        image:
          - boca-base
        parent: ${{ fromJSON(needs.setup.outputs.parent) }}
    with:
      image: ${{ matrix.image }}
      parent: ${{ matrix.parent }}
      is_default_parent: ${{ needs.setup.outputs.default_parent == matrix.parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: 'debug'
    needs:
      - setup

  build-web:
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        parent: ${{ fromJSON(needs.setup.outputs.parent) }}
    with:
      image: boca-web
      parent: ${{ matrix.parent }}
      is_default_parent: ${{ needs.setup.outputs.default_parent == matrix.parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: 'debug'
    needs:
      - setup
      - build-base

  build-jail:
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        parent: ${{ fromJSON(needs.setup.outputs.parent) }}
    with:
      image: boca-jail
      parent: ${{ matrix.parent }}
      is_default_parent: ${{ needs.setup.outputs.default_parent == matrix.parent }}
      platforms: ${{ needs.setup.outputs.platform }}
      tag: 'debug'
    needs:
      - setup
      - build-base
